version: '3.3'
services:

    opensearch:
        ports:
            - '9200:9200'
            - '9600:9600'
        environment:
          discovery.type: 'single-node'
        image: 'opensearchproject/opensearch:2.4.0'
        networks:
            - drdroid

    opensearch-dashboards:
        ports:
            - '5601:5601'
        expose:
            - '5601'
        environment:
           OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
        image: 'opensearchproject/opensearch-dashboards:2.4.0'
        depends_on:
            - opensearch
        networks:
            - drdroid

    redis:
        image: 'redis:alpine'
        ports:
          - '6379:6379'
        networks:
          - drdroid

    init-corellian:
        image: 'public.ecr.aws/y9s1f3r5/drdroid/corellian:latest'
        depends_on:
          - opensearch
          - opensearch-dashboards
          - redis
        entrypoint: [ '/bin/sh', '-c' ]
        environment:
          redis_url: redis
          ops_servers: opensearch:9200
          ops_dash_servers: opensearch-dashboards:5601
        command: |
          "
          python setup_index.py
          "
        networks:
          - drdroid

    corellian:
        image: 'public.ecr.aws/y9s1f3r5/drdroid/corellian:latest'
        environment:
          redis_url: redis
          ops_servers: opensearch:9200
          ops_dash_servers: opensearch-dashboards:5601
        ports:
          - 8082:8082
        depends_on:
          - opensearch
          - opensearch-dashboards
          - redis
        networks:
          - drdroid

    kenobi:
        image: 'public.ecr.aws/y9s1f3r5/drdroid/kenobi:latest'
        environment:
          ops_servers: opensearch:9200
          ops_dash_servers: opensearch-dashboards:5601
          redis_url: redis
        depends_on:
          - opensearch
          - opensearch-dashboards
          - redis
        networks:
          - drdroid

networks:
    drdroid:
        driver: bridge

